#!/bin/bash
cd "$(dirname "$0")"

source ./color_constants

# \b = backspace
# because of variable can echo near with normal text, so I space them and backspace to back
printf "$RED \bthis$RESET $BLINK_RED \bis$RESET $HI_PURPLE \bcolor$RESET $U_GREEN \btester$RESET on $BLINK_PINK \bprintf$RESET.\n"
echo "$RED \bthis$RESET $BLINK_RED \bis$RESET $HI_PURPLE \bcolor$RESET $U_GREEN \btester$RESET on $BLINK_PINK \becho$RESET.\n"
echo -e "$RED \bthis$RESET $BLINK_RED \bis$RESET $HI_PURPLE \bcolor$RESET $U_GREEN \btester$RESET on $BLINK_PINK \becho$RESET with $BLINK_BLUE \b-e$RESET.\n"
